apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.36.0
  name: kustomize-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.36.0
  name: cluster-reconciler-flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: flux-installer
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.36.0
spec:
  completions: 1
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: flux
        image: ghcr.io/fluxcd/flux-cli:v0.36.0
        env:
        - name: "{{ .Params.gitTokenName }}"
          value: "{{ .Params.gitToken }}"
        args:
        - bootstrap
        - "{{ .Params.type }}"
        - --owner={{ .Params.owner }}
        - --repository={{ .Params.repository }}
        - --path={{ .Params.path }}
        - --private={{ .Params.private }}
        - --personal={{ .Params.personal }}
      restartPolicy: Never
      serviceAccountName: kustomize-controller