apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: io
versions:
  kubernetes: "1.24.7"
clusterNetwork:
  podSubnet: "172.25.0.0/16"
  serviceSubnet: "10.240.16.0/20"
  cni:
    external: {}
cloudProvider:
  hetzner: {}
  external: true
containerRuntime:
  containerd: {}
addons:
  enable: true
  path: "./addons"
  addons:
    - name: calico-vxlan
      params:
        MTU: "1400"
    - name: cluster-autoscaler
    - name: default-storage-class
    - name: backups-restic
      params:
        resticPassword: xxx
        s3Bucket: io.kubeone
        awsDefaultRegion: eu-central-1
    - name: flux
      params:
        gitTokenName: "GITHUB_TOKEN"
        gitToken: "env:GITHUB_TOKEN"
        type: "github"
        owner: ""
        repository: ""
        path: ""
        private: "false"
        personal: "true"
    #- name: "operating-system-manager"
